### ISSUE TITLE
Suggestion naming convention

### ISSUE THREAD

**Issue by lgrozinger** [intbio-ncl/shortbol#10]
With the new template composition capability starting from 2e4c57b81724ae4b2023556722c9500d1c1ad92e , there are now two kinds of template in the SBOL library:

1. Those intended to be used to instantiate objects that are named with their own URI.
2. Those intended to only ever be used to extend or modify another template or instance.

For an example of 1, `Sequence`.
For an example of 2, `hasSequence`.

https://github.com/intbio-ncl/shortbol/blob/refactor_templatepy/templates/sbol/sequence.rdfsh

Most templates in the SBOL library are of  type 1 and begin with uppercase letters. My suggestion is to make it a convention that those of type 2 begin with lowercase. (`Sequence` and `hasSequence` conform to this).

Discussion or discord welcome.

**Comment by MattyCrowther** [comment]
Edit link to style guide can be found at 
https://www.overleaf.com/8765198122pfwyxxjzschc

**Comment by MattyCrowther** [comment]
Closing this as it isn't an issue anymore, we have documentation of a style guide, if the tool becomes used we can pick this back up
