### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by lgrozinger** [intbio-ncl/shortbol#12]
Can I suggest that a permissive license such as MIT is the most appropriate.

Is there any strong feeling one way or another?

**Comment by jakebeal** [comment]
A permissive like MIT or BSD would be fine.  The other alternative that I generally also suggest considering is GPL-with-linking-exception (https://en.wikipedia.org/wiki/GPL_linking_exception), which is permissive for usage, but requires sharing for the code itself.
