### ISSUE TITLE
Self overwritting lhs of Identifier.

### ISSUE THREAD

**Issue by MattyCrowther** [intbio-ncl/shortbol#18]
```
sequenceConstraint(componentDefinition_subject,componentDefinition_object,restriction)
(
 self._.componentDefinition_subject._c is a Component(componentDefinition_subject)
 self._.componentDefinition_object._c is a Component(componentDefinition_object)

 component = self._.componentDefinition_subject._c
 component = self._.componentDefinition_object._c
  
 self._.componentDefinition_subject._c._.restriction._.self._.componentDefinition_object._c  is a SequenceConstraint(self._.componentDefinition_subject._c, self._.componentDefinition_object._c , restriction)
 sequenceConstraint = self._.componentDefinition_subject._c._.restriction._.self._.componentDefinition_object._c 
)
```

**Comment by lgrozinger** [comment]
Can you also include an example of creating an instance of this template which reproduces the bug?

**Comment by MattyCrowther** [comment]
cas9m_BFP_gene is a Promoter()
(
    sequenceConstraint(pConst,cas9m_BFP_cds,i_precedes)
)

**Comment by lgrozinger** [comment]
I'm still having trouble reproducing the problem. The following works fine on master:
```

@prefix my = <my/>
@prefix my

SequenceConstraint(subject, object, restriction)
(
  subject = 1
  object = 2
  restriction = 3
)

sequenceConstraint(componentDefinition_subject,componentDefinition_object,restriction)
(
 self._.componentDefinition_subject._c._.restriction._.self._.componentDefinition_object._c  is a SequenceConstraint(self._.componentDefinition_subject._c, self._.componentDefinition_object._c , restriction)
)

S()
(
  sequenceConstraint(<subject>, <object>, <restriction>)
)

s is a S()
```

Any help or insight appreciated.

**Comment by lgrozinger** [comment]
Actually, the above works fine in master, but not on m_crowther_development --- which is 3 commits behind!

**Comment by MattyCrowther** [comment]
So, the issue is persisting even with the revert. 
So I reverted, changed to m_crowther_development pulled your new one-line change and removed all the modifications I made to rdfscript over the last month (wasn't much) and tried again. The error still occurs.
So I have a hypothesis about the error.
When the SequenceAnnotation is created it is created with an incorrect identifier:

` <http://sbol_prefix.org/mKate_gene_gRNA_b_nc_c_i_precedes_http://sbol_prefix.org/mKate_gene_mKate_cds_c> `

So what self is doing is taking the whole namespace and pre-amble as well which is means that when self is handled in the middle of a dotted list we end up with:
```
http://sbol_prefix.org/mKate_gene_gRNA_b_nc_c_i_precedes_
http://sbol_prefix.org/mKate_gene_mKate_cds_c
```

Perhaps something is detecting this and cutting leaving only:

`http://sbol_prefix.org/mKate_gene_mKate_cds_c`

you can see this on the m_crowther dev branch with example 
examples/examples_abstraction_layer_2_composite_sequence_constraint_multiple_end.shb

**Comment by MattyCrowther** [comment]
Perhaps this is done when an assignment is made or because it is assigned because the overwrite of the identifier only occurs if the assignment is made, if the instance is created but not assigned there is no error.

**Comment by MattyCrowther** [comment]
So, I believe I have fixed the issue, maybe not the most elegant solution but it appears to work.
The problem was:
When self is found not only does it add the identity but also the namespace/prefix.
So something like:
let the current scope = s
let the prefix = "<http://sbol_prefix.org/>"
let a = a
let b = b
self.a._.self.b would resolve to 
<http://sbol_prefix.org/>s_a_<http://sbol_prefix.org/>s_b

So you can see that self is substituted with namespace + parent_scope.


This caused:
So this was not an issue when there was no assignment because it wouldn't be evaluated by parts of the SBOL extension.
URI has a method named: split which splits up the URI.
SBOL uses this to set certain properties.
Because it is designed to essentially remove the namespace what it does it find the second namespace in the string and cut the LHS of this resulting in the loss.
The fix was:
I added this code in the Template. evaluate method:
`                if isinstance(part,Uri) and i > 0:
                    try:
                        if context.prefix_for_uri(part) in str(part):
                            continue
                    except PrefixError:
                        pass`

This basically checks if the prefix is in the part and continues so doesn't add it to the final structured URI.
I think there is a better solution than this maybe stop this situation from ever happening.
The fix is on the m_crowther_development branch.
