### ISSUE TITLE
A syntax for a 'using' expression or equivalent.

### ISSUE THREAD

**Issue by lgrozinger** [intbio-ncl/shortbol#27]
Would be good, as pointed out by @MattyCrowther, to have a way to refer to templates, variables in another file/namespace (with a different prefix) in my own namespace. So that:
```

use <sbol>
something is a sbol.Component()
```

becomes

```
using <sbol>
something is a Component()
```

This (I think) can be done currently using

```
use <sbol>
Component = sbol.Component
something is a Component()
```

So the new construct, which I am calling 'using' for the moment, would do that second line for every template in sbol for the user.

**Comment by lgrozinger** [comment]
After this is done, a rename of the two things might be in order. I expect renaming 'use' to 'include' and 'using' to 'use' would break the least stuff in the template library.

**Comment by MattyCrowther** [comment]
#29 Fixed
